export { default as AboutSection } from "./about-section";
export { default as ContactSection } from "./contact-section";
export { default as HeroSection } from "./hero-section";
export { default as ServicesSection } from "./services-section";
export { default as StrategiesSection } from "./strategies-section";
export { default as TeamSection } from "./team-section";
export { default as PartnershipsSection } from "./partnerships-section";
export { default as WhyChooseUsSection } from "./why-choose-us-section";
export { default as TradingPlatformsSection } from "./trading-platforms-section";
